
== Abstract (Deutsche Version)
Der Ziel der folgenden Diplomarbeit war, eine Lernplattform für Mitarbeiter einer Softwarefirma zu entwicklen. Anfangs haben wir die verschiedenen Arten wie Menschen lernen genauer betrachtet, und diese zu Lerntypen zusammengefasst. (Vester, Pask, Dunn,) Darüber sind wir auf das Thema "Wissensmanagement" näher eingegangen, und haben identifiziert, was Menschen mit ihrem Wissen anstellen. Diese Beiden Fachgebiete haben wir in unsere Website einfließen lassen, und diese so aufgebaut, dass sich Mitarbeiter Kurse anschauen können und mit dem daraus gewonnenen Wissen Quizze beantworten sollen. Das besondere hierbei ist, dass jeder "Spieler" Punkte und Embleme für richtig beantwortete Fragen bekommt. Dadurch können sich diese miteinander vergleichen und anspornen die meisten Punkte zu gewinnen. Somit ist ein spielerischer Faktor inkludiert, der dem Lernerfolg hilft.


== Abstract (Englische Version)
In the following diploma thesis, we created a learning platform for employees of a software firm. In the beginning, we looked at the different ways to learn, which are summarized in learning types. Furthermore we looked into knowledge management and what people do with their knowledge. With these two factors in mind, we built a web-page, where employees are able to learn different programming-skills by taking courses and answering quizzes. The special thing about this tool is, that everyone is rewarded points and icons for correct answered questions. This way, employess can match and compare each other and so a playful factor is included.