== Praktische Aufgabenstellung: Eric Haneder

== Front End: Design und Graphic User Interface

=== Beginning
Nachdem die Technologie festgelegt war, mit der die Website programmiert werden sollte, konnten wir anfangen.
Zuerst muss aber mit dem Auftraggeber ein Design abgeklärt werden, welches ihm zusagt, und für uns umsetzbar ist.

Hier ist ein abstraktes Diagramm der User-Interfaces:
<Bild einfügen>

//image::Trainee Interface (1).png[]


Nachdem auch das Design abgeklärt war, konnte nun die Erstellung der Interfaces beginnen.

=== Grundlagen
Um eine Website zu programmieren, benötigt man ein Menge an umfangreichen Wissen. Man muss html, javascript und css beherschen. Darüber hinaus sollte man auch wissen, wie aus dem Code eine fertige Seite erzeugt wird, und wie Requests vom User ausgewertet und darauf geantwortet werden kann.

==== HTML
Hypertext Markup Language (HTML) is the common used language for building web pages. A HTML page is a text document (with a .html or .htm extension) used by browsers to present text and graphics. A web page is made of content, tags to change some aspects of the content, and external objects such as images, videos, JavaScript, or CSS files.

.Beispielcode für eine html page
[source, html]
----
<html>
    <head>
        <title>My Webpage</title>
    </head>
    <body>
        <h1>This is my webpage</h1>
        <p>
            I hope you like it.
        </p>
        <a href="www.google.at">Link to Google</a>
    </body>
</html>
----
NOTE: U can notice several tags in this code (such as <body> or <p>). Every tag has its on purpose, attributes and must be closed. Href is an attribute of the a-tag.

XHTML is just a validated version of html. This means, that there are certain rules, a html-page has to follow, to be valid. XHMTL pages have a .xhtml extension.

Some of the rules are the following:

* All tags must be closed. (so no <br>, <hr>, ...)
* All tags are lowercase.
* Attributes appear appear between single or double quotes (<table border="0"> instead of <table border = 0>)
* There must be a strict structure with <html>, <head> and <body> tags.

==== CSS
Cascading Style Sheets (CSS) is a styling language used to describe the presentation of a document written in html or xhtml. CSS is used to define colors, fonts layouts, and other aspects of document presentation.It allows separation of a document’s content (written in XHTML) from its presentation (written in CSS).
To embedd a .css file in your html or xhtml page, use the <link> tag.
(e.g. <link rel="stylesheet" type="text/css" ?

.Your css file could look like this:
[source,css]
----
p {
    font-size: 10px;
}
h1 {
    color: red;
    font-style: italic;
}
----


=== Getting Started
==== Projektstruktur erstellen
Um mit dem Programmieren zu beginnen, muss erst eine stabile Projektstruktur gegeben sein. Dafür haben wir in NetBeans auf "Projekt erstellen" geklickt, alle benötigten Resourcen vereinbart, und mit Maven wurde dann automatisch eine passende Projektstruktur erstellt.
Nun muss man auch darauf achten, dass diese Struktur befolgt.
Java-Dateien sollten unter src\main\java abgelegt werden.
Everything regarding JSF should lie in src\main\webapp. That includes the xhtml-files, the CSS, JavaScript and Images should lie in a untergeordnetem resources folder. This is needed, for JSF to locate the resources faster.
<Bild einfügen, welches die Projektstruktur zeigt>

==== Layout erstellen
Um die Erstellung mehrerer UIs zu vereinfachen, wird ein Layout erstellt, welches als ein Template für die Pages dient.
Dieses Layout habe ich in der mainlayout.xhtml realisiert.

:sourcedir: src/main/webapp

[source, xhtml]
----
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:f="http://java.sun.com/jsf/core"
      xmlns:p="http://primefaces.org/ui">
    <h:head> 
        <!--<link href="http://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.3.0/css/font-awesome.css" 
            rel="stylesheet"  type='text/css'></link> -->
    </h:head>
    <h:body>
        <div id="header">
            <h:graphicImage library="img" name="header.png" style="width: 100%"></h:graphicImage>
        </div>
        
        <ui:insert name="menubar">
            <ui:include src="./faces/menubar.xhtml"></ui:include>
        </ui:insert>
        
        <ui:insert name="header">
            <h:outputStylesheet library="resources" name="css/stylesheet.css"></h:outputStylesheet>
        </ui:insert>
        <br />
        
        <ui:insert name="content">
            Content
        </ui:insert> 
        <br />
        
        <h:graphicImage library="img" name="footer1.jpg" style="margin: 0px 0px 0px 0px;"></h:graphicImage>
    </h:body>
</html>
----




[source,xhtml]
----
include::../../game-trainee-web/src/main/webapp/mainlayout.xhtml[]
----

<Bild einfügen>

.Erklärung
 Anfangs wird dem Browser die Information weitergegeben, dass es sich um eine xhtml Datei handelt. Weiters werden die Buchstaben h, ui, f und p definiert, die alle auf eine jsf-library verweisen (Diese Verweise sind nötig, damit der Browser die JSF-Tags lesen kann.
 Im head wird hier keine Information definiert (!).
 Im body wird eine Logo angezeigt, mit einer Überschrift daneben (<h1>).
 Der div-tag ist nur dazu da, um einen Bereich abzugrenzen, und diesen dann mit CSS zu positionieren/formatieren.
 Mit <ui:insert> gibt man im mainlayout Informationen an, die die Clients des Layouts individuell einbauen, oder überschreiben wollen.
 <h:outputStylesheet> wird zum Verknüpfen der CSS-Datei verwendet.
 Mit <ui:include> können wir Informationen einer anderen Page, in diese Page einbauen.
 Im footer-Bereich werden noch Kontaktdaten angezeigt.

=== User-Interfaces
Die UIs liegen hier unter src\main\webapp\faces. There are 4 main pages: Activites(index.xhtml), Courses & Quizes(courses.xhtml), Trainers(trainers.xhtml) and a leaderboard(leaderboard.xhtml.
Die erste zu erstellende Seite, ist die index.xhtml Seite, da diese standardmäßig vom Browser zuerst angezeigt wird, beim aufrufen der Website.
Auf der Startseite sollte der User seinen Fortschritt und seine Aktivitäten sehen.

.index.xhtml
[source,xhtml]
----
include::../../game-trainee-web/src/main/webapp/faces/index.xhtml[]
----
As you can see, the index-page is using the mainlayout with the "template" attribute. We defined a individell title with <ui:define>. The content of this page is enclose in <ui:define> too.
We dont need to set a footer here, because in the template page, there is already an universal footer defined.

The Courses&Quizes page should display a list of course the trainee can go through and a list of quizes a trainee can take. Trainers should be able to add, delete and edit quizzes.

.courses.xhtml
[source,xhtml]
----
include::../../game-trainee-web/src/main/webapp/faces/courses.xhtml[]
----

At the the end there is a <h:link> tag. This is a JSF tag that resolves in to an <a> tag, leading to another page.
There is a link that leads to a page where you can take a quiz, and there is a link where you can create a quiz. More on that later.

The Trainers page should display all the trainers associated with the GAME platform. The trainees can contact these trainers if they need help.

.trainers.xhtml
[source,xhtml]
----
include::../../game-trainee-web/src/main/webapp/faces/trainers.xhtml[]
----


Here we used a primefaces tag called <p:carousel>. This tag is used to create a carousel. The <panelGrid> tag is used to display data in a grid. The <p:graphicImage> is just like the JSF tag <h:graphicImage>. <h:outputText> is used to display text, with the function to call a Backing Bean. For easier explanation here is a picture:
Bild einfügen
 
The leaderboard page is used to diplay all the trainees with their names, nicknames, branches and scored. You should be able to sort them by all of this columns.
 
.leaderboard.xhtml
[source,xhtml]
----
include::../../game-trainee-web/src/main/webapp/faces/leaderboard.xhtml[]
----

Here we used the <p:dataTable> tag, which is used to display date just like in the regulare <table> tag. If you give it a list, it will know to diplay all elements of the list.

=== Java Classes

==== Trainer Classes

----

.TrainerService.java
[source,java]
----
include::../../game-trainee-web/src/main/java/org/game/trainee/trainerview/TrainerService.java[]
----

.TrainerView.java
[source,java]
----
include::../../game-trainee-web/src/main/java/org/game/trainee/trainerview/TrainerView.java[]
----

==== Trainee Classes

----

.TraineeView.java
[source,java]
----
include::../../game-trainee-web/src/main/java/org/game/trainee/traineeview/TraineeView.java[]
----

.TraineeGenerator.java
[source,java]
----
include::../../game-trainee-web/src/main/java/org/game/trainee/traineeview/TraineeGenerator.java[]
----

==== Quiz Classes










