[[section-Stakeholders]]

== Stakeholders
[role="stakeholders"]

* *Thesis supervisor* (contractor side)*:* Roland Moder roland.moder@aon.at
* *Thesis supervisor* (client side)*:* Konrad Renner konrad.renner@arz.at
* *Human resource development:* Michaela Würzl michaela.wuerzl@arz.at, 
Cornelia Sammer cornelia.sammer@arz.at

*_Expectations_*:

pass:[<u>Roland Moder</u>]: +
He expects the diploma thesis to run smoothly and be completed within a reasonable time, this means it has to be completed by the end of April. Additionally, the diploma students should fulfill the requirements for a diploma thesis. Furthermore, there should be a sufficient documentation of the work done.


pass:[<u>Konrad Renner</u>]: +
He expects the software to contain a scoring system that records the learning progress of every member, which can be evaluated and compared. Furthermore, he expects to be able to mantain the tasks independently, this means if all tasks have been fulfilled on the platform, there should be an opportunity for coaches to be able to put in new tasks. 


pass:[<u>Michaela Würzl & Cornelia Sammer</u>]: +
They expect a timely completion of the project, so that the concept is completed by 31.12.2019, and the implementation should be completed by the end of April. Moreover, the software should be utilizable and integrable, this means the user interface should be easy to use for employees, trainers and moderators.

