== Summary

To conclude our diploma thesis, I will point out what worked well, what did not and how our overall experience was.

The co-operation with the ARZ was professional and informative. We met with the contact person of the client every two weeks in so called "sprint-meeting". Our contact person was Konrad Renner, who is also one of the stakeholders of the project, so he knew exactly how the system should look like. In this meetings we discussed problems which occured and set new goals which should be achieved in the next two weeks. The time between the meetings is called a sprint. By doing this, we stayed productive all the time and our workcycle was very dynamic. If we had problems working out our tasks Mr. Renner was always there, to provide guidance. The working atmosphere at the ARZ was peaceful and we were always treated with respect and kindness by the employees who were working there.

In the process of the diploma thesis, we learned a lot about programming with Java EE and programming skills in general. To put it more specific, I leaned some key insights on how to poperly program a website with a modern design and smart user interfaces. Jan got to learn everything surrounding a database and how to manage data. Furthermore, the "sprints" we did throughout the duration of the project has shown us how software developers manage projects. In addition, by writng the diploma thesis in english, our english skills improved a lot.

In general, we had a lot of problems programming the website, because we lacked some certain key knowledge about the software we were using. In school we were provided with some overall programming knowledge, but we did not quite get the connections. We did learn how to program in Java SE, but building a website with Java EE is more complicated than we thought. This lead to us having to instensively learn wide parts of the software we used.

The outcome is a prototype, which can be implemented into the digital infrastructure of the ARZ. Employees are able to improve their java-skills by taking quizzes and courses regarding certain java topics. They will be rewarded with points and emblems, with adds game-elements to the platform. This way, the learning process of the trainees is eased. Trainers can add new courses/quizzes to the database to provide new learning material.

Our thesis can give schools ideas for adapting and optimizing their teaching methods. A good start would be to try to implement "Gamificated Learning" in their schedule. Currently, the way students learn is shifting due to the ongoing pandemic. With everything being in motion, teachers could detach from old habits and implement new elements in their teaching methods. Gamificated learning would is a major milestone in the history of teaching. I do not think that pure frontal teaching is the right way to go and I hope the school system will improve in the future.

