= Theoretische Aufgabenstellung: Eric Haneder

= Lernen, Lerntypen und selbstreguliertes Lernen
== Lernen

Jeder Mensch kommt nicht darum herum zu lernen. Sei es in der Schule oder im Berufsleben, sich weiterzubilden gehört zum Wesen des Menschen. Unter dem Begriff "Lernen" versteht man normalerweise die Aneignung von Wissen, den Aufbau von Fertigkeiten oder die Einübung motorischer Abläufe. Mit "Lernen" werden aber ebenso Tätigkeiten bezeichnet, welche mit dem Ziel einer Veränderung interner Bedingungen durchgeführt werden.

_(vgl. Selbstreguliertes Lernen in der dualen Ausbildung - Lerntypen und Bedingungen, Johannes Rosendahl, 2010)_


*Wie genau also lernt der Mensch?*

Um diese Frage zu beantworten, muss man sich die verschiedenen Lerntypen genauer anschauen. Frederick Vester hat mit seinem Buch "Denken, Lernen, Vergessen. Was in unserem Kopf vor, wie lernt das Gehirn, und wann lässt es uns im Stich?" (1975, Stuttgart) diese Lerntypen definiert. Jedoch wurde sein Buch unterschiedlich aufgefasst, sodass verschiedene Versionen seiner Einteilung auffindbar sind. Zumindest bei dem Fakt, dass es einen auditiven, einen visuellen und einen haptischen Lerntyp gibt, ist man sich einig. Jedoch gibt es einige Menschen, die meinen, der vierte Lerntyp nach Frederik Vester, wäre der kommunikative Lerntyp und andere meinen einen intellektuellen Lerntyp. 

 (Man stößt auch noch auf Begriffe wie "kognitiver Lerntyp" ≙ "intellektueller Lerntyp", oder den "kinästhetischen Lerntyp" ≙ "haptischer Lerntyp") 

.Nachweise für 4 Lerntypen nach Vester mit "kommunikativem Lerntyp"
 https://www.teko.ch/die-vier-lerntypen-und-ihre-besonderheiten;
 https://www.mystipendium.de/studium/lerntypen;
 https://karrierebibel.de/lerntypentest/#Die-vier-Lerntypen-angelehnt-an-Frederic-Vester;
 https://learnsolution.de/die-vier-lerntypen-nach-frederic-vester/;
 
.Nachweise für 4 Lerntypen nach Vester mit "intellektuellem Lerntyp"
 http://www.rechtschreibwerkstatt-konzept.de/wp-content/uploads/2015/02/Looss_Lerntypen.pdf;
 https://wb-web.de/wissen/lehren-lernen/lernstile-und-lerntypen.html;
 https://smarter-learning.de/lerntypen/klassische-lerntypen-nach-vester/;
 https://wissenschafts-thurm.de/lerntypen/;
 "Erforschung der Lerntypen und -strategien am Beispiel einer Handelsschulklasse", Petra Hochleitner, 2016 
 
Ich werde mich in dieser Analyse, auf diese Interpretation der Einteilung der Lerntypen nach Vester stützen:

1. optisch/visuell -> Lernen durch Sehen und Beobachten
2. auditiv/akkustisch -> Lernen durch Hören und Sprechen
3. Haptisch -> Lernen durch Handeln (Anfassen und Fühlen)
4.  Kognitiv -> Lernen durch Erkennen/den Intellekt

Man kann den meisten Menschen keinen eindeutigen Lerntyp zustellen, da es viele Lern-Mischtypen gibt. Das heißt jemand lernt etwas schneller, indem er es sich durchliest und wieder aufschreibt (optisch & haptisch), ein wieder andere lernt durch eine Kombination des auditiven und haptischen besser.

Wenn man also effektiv lernen will, sollte man versuchen so viele Sinne wie möglich anzusprechen, um den Lernerfolg zu erhöhen.

*Wie kann man also herausfinden welcher Lerntyp einem am besten steht?*

Im Internet findet man viele sogenannte Lerntypentests. Hier sind zwei Hyperlinks, die zu etwas einfachereren Tests führen:

* http://arbeitsblaetter.stangl-taller.at/TEST/HALB/Test.shtml
* http://www.philognosie.net/index.php/tests/testsview/150/

Nach Abschluss eines dieser Tests, bekommt man eine Empfehlung, welcher Lerntyp mehr auf einen zutrifft.

NOTE: Anzumerken ist, dass bei verschiedenen Test auch verschiedene Empfehlungen rauskommen können. Das liegt daran, dass die Tests unterschiedliche Schwerpunkte aufweisen und mehr oder weniger umfangreich sind. 

Wie bereits erwähnt, trifft auf eine Person meistens nicht ein Lerntyp zu, sondern mehrere.

Dabei hilft nur der "Try and Error" Prozess. Durch das Ausprobieren verschiedener Lernmethoden (z.B.: Stichwortkarten, Lesen, Merken & Wiedergeben, ...) findet man schlussendlich eine Methode, die einem am meisten hilft. Wenn man sich nicht damit abmühen will, seinen Lerntyp abzutesten, kann man auch well-approved Lernmethoden ausprobieren, die möglichst viele Sinne ansprechen.

_(vgl. "Erforschung der Lerntypen und -strategien am Beispiel einer Handelsschulklasse", Petra Hochleitner, 2016)_

== Wofür braucht man Lerntypen?
Jeder kann sich anhand den Lerntypen orientieren, und sich selber einen oder mehrere dieser zuordnen. Wenn man das geschafft hat, kann man anhand dieser Lernmethoden entwickelen (oder vorhandene nehmen), um den persönlichen Lernerfolg zu steigern.

== Woher kommt die Einteilung?

== Auditiver Lerntyp
Der auditive Lerntyp lernt am besten über sein Gehör. 

== Optischer Lerntyp

== Haptischer Lerntyp

== Kognitiver Lerntyp

= Wie lernt man richtig?
Eine Standardregel die weit verbreitet ist besagt, dass man nicht am Tag vor einer Prüfung anfangen sollte zu lernen, da am nächsten Tag nicht viel Gelerntes hängen bleibt.
(Bei mir is es zwar anders aber ok.)

= Selbstreguliertes Lernen

Der Begriff des selbstreguliertem Lernens, ist weder ein präziser wissenschaftlicher definierter Begriff, noch eine einheitliche gebrauchte alltagssprachliche Bezeichnung. Weiters kann man die Begriffe self-regulated learning, self-directed learning, learner control kaum schlüssig abgrenzen.

Niegemann und Hofer (1997) oder Büser (2003) definieren, dass beim selbstbestimmten Lernen das Lernziel im Gegensatz  zum selbstgesteuerten bzw. –regulierten Lernen von der Person selbst bestimmt wird. Andere Autoren hingegen sehen das Entscheiden über die Lernziele explizit als Bestandteil selbstgesteuerten bzw. -regulierten Lernens (Arnold & Gomez-Tutor 2006; Dehnbostel 2003; Lang & Pätzold 2006; Neber 1978; Schreiber 1998, S. 45).



_(vgl. Selbstreguliertes Lernen in der dualen Ausbildung - Lerntypen und Bedingungen, Johannes Rosendahl, 2010)_




