= Theoretische Aufgabenstellung: Eric Haneder

= Lerntypen

Jeder Mensch kommt nicht darum herum zu lernen. Sei es in der Schule oder im Berufsleben, sich weiterzubilden gehört zum Wesen des Menschen.
Wie genau also lernt der Mensch?
Um diese Frage zu beantworten, muss man sich die verschiedenen Lerntypen genauer anschauen.

Es gibt vier Lerntypen (nach Frederic Vester):

* optisch/visuell -> Lernen durch Sehen
* auditiv/akkustisch -> Lernen durch Zuhören
* Haptisch -> Lernen durch Handeln
* Kognitiv -> Lernen durch Erkennen

Man kann den meisten Menschen keinen eindeutigen Lerntyp zustellen, da es viele Lern-Mischtypen gibt. Das heißt jemand lernt etwas schneller, indem er es sich durchliest und wieder aufschreibt (optisch & haptisch), ein wieder andere lernt durch eine Kombination des auditiven und haptischen besser.

Wenn man also effektiv lernen will, sollte man versuchen so viele Sinne wie möglich anzusprechen, um den Lernerfolg zu erhöhen.

Wie kann man also herausfinden welcher Lerntyp einem am besten steht?
Im Internet findet man viele sogenannte Lerntypentests. Hier sind zwei Hyperlinks, die zu etwas einfachereren Tests führen:

* http://arbeitsblaetter.stangl-taller.at/TEST/HALB/Test.shtml
* http://www.philognosie.net/index.php/tests/testsview/150/

Nach Abschluss eines dieser Tests, bekommt man eine Empfehlung, welcher Lerntyp mehr auf einen zutrifft. Anzumerken ist, dass bei verschiedenen Test auch verschiedene Empfehlungen rauskommen können. Das liegt daran, dass die Tests unterschiedliche Schwerpunkte aufweisen und mehr oder weniger umfangreich sind. 
Wie bereits erwähnt, trifft auf eine Person meistens nicht ein Lerntyp zu, sondern mehrere.

Dabei hilft nur der "Try and Error" Prozess. Durch das Ausprobieren verschiedener Lernmethoden (z.B.: Stichwortkarten, Lesen, Merken & Wiedergeben, ...) findet man schlussendlich eine Methode, die einem am meisten hilft. Wenn man sich nicht damit abmühen will, seinen Lerntyp abzutesten, kann man auch well-approved Lernmethoden ausprobieren, die möglichst viele Sinne ansprechen.




(vgl. "Erforschung der Lerntypen und -strategien am Beispiel einer Handelsschulklasse", Petra Hochleitner, 2016)

== Wofür braucht man Lerntypen?
Jeder kann sich anhand den Lerntypen orientieren, und sich selber einen oder mehrere dieser zuordnen. Wenn man das geschafft hat, kann man anhand dieser Lernmethoden entwickelen (oder vorhandene nehmen), um den persönlichen Lernerfolg zu steigern.

== Woher kommt die Einteilung?

= Auditiver Lerntyp

= Optischer Lerntyp

= Haptischer Lerntyp

= Kognitiver Lerntyp

= Wie lern man richtig?
Eine Standardregel die weit verbreitet ist besagt, dass man nicht am Tag vor einer Prüfung anfangen sollte zu lernen, da am nächsten Tag nicht viel Gelerntes hängen bleibt.
(Bei mir is es zwar anders aber ok.)



