= GAME - Gamificated ARZ Member Education

= Introduction and Goals


The ARZ  wants to find a way for a more intelligent, advanced and playful further education. The workers often have different knowledge about programming, so it is rather time consuming and costly to further educate them.

This is where the idea of "GAME" comes into play. The "GAME" is intended to be a platform on which employees can improve their programming knowladge with little games, quizzes or competitions.

A great focus lies on the terms "self-study" and "Gamification". Gamification means that the information is transmittetd through games to ease the learning process. 

Furthermore there should be a possibility for trainers to bring in their own ideas, quizzes or modules. One of the goals of this diplome thesis is to motivate the people to continue their education in their free time. There should be a possibility to learn some skills without much effort. 

Another important aspect of "GAME" is the scoring system, which will be implemented in the software. This will create transparency for employees and employers. This scoring system will be a great motivation for workers. 

The most relevant Stakeholders are the following:


* Roland Moder 

* Konrad Renner

* Michaela Würzl

NOTE: The expections of the Stakeholders should be fulfilled. 

The expectations of the stakeholders regarding the thesis are: 

* sufficient documentation regarding the arc42 template 
* Fulfillment of the quality goals
* a clear and well-functioning software
* an easy-to-use user interface


---

= Aufgabenstellung
...

= Qualitätsziele
...

= Stakeholder

* *Diplomarbeitsbetreuer* (Auftragnehmerseite)*:* Roland Moder roland.moder@aon.at
* *Diplomarbeitsbetreuer* (Auftraggeberseite)*:* Konrad Renner konrad.renner@arz.at
* *Personalentwicklung:* Michaela Würzl michaela.wuerzl@arz.at, 
Cornelia Sammer cornelia.sammer@arz.at




[cols="1,1,2" options="header"]
|===
|Rolle |Kontakt |Erwartungshaltung
| Diplomarbeitsbetreuer | Roland Moder | Von diesem Stakeholder wird erwartet, dass die Diplomarbeit reibungslos verläuft und in angemessener Zeit fertiggestellt wird. Er ist zuständig dafür, dass die Diplomanden ausreichend dokumentieren und die Anforderungen für eine Diplomarbeit erfüllen. 
| Diplomarbeitsbetreuer | Konrad Renner | Von diesem Stakeholder wird erwartet, dass die Diplomanden die Aufgabenstellung richtig verstanden haben, und nach seinen Vorstellungen umgesetzt werden. Er muss die Architektur des Projekts kennen und trifft aufgrunddessen wichtige Entscheidungen um die Diplomarbeit zu lenken bzw. zu steuern. Er ist die Ansprechsperson für die Diplomanden falls Unklarheiten bei der Programmierung o.Ä. auftreten.   
| Personalentwicklung | Michaela Würzl | Die Diplomarbeit "läuft" über die Personalabteilung, also ist die Personalchefin sozusagen das Oberhaupt der Diplomarbeit seitens der Firma. Sie erwartet sich ein ordentliches Ergebnis und muss von dem Projekt überzeugt werden.   
|===