[[section-Introduction]]

== Introduction and Goals
[role="introduction"]

The ARZ wants to find a way for a more intelligent, advanced and playful further education. ARZ means "Allgemeines Rechenzentrum" and it is a IT service provider with a location in Innsbruck and Vienna. Their homepage: https://www.arz.at/

The workers often have different knowledge about programming, so it is rather time consuming and costly to further educate them.

This is where the idea of "GAME" comes into play. The "GAME" is intended to be a platform on which employees can improve their programming knowladge with little games, quizzes or competitions.

A great focus lies on the terms "self-study" and "Gamification". Gamification means that the information is transmittetd through games to ease the learning process. 

Furthermore there should be a possibility for trainers to bring in their own ideas, quizzes or modules. One of the goals of this diplome thesis is to motivate the people to continue their education in their free time. There should be a possibility to learn some skills without much effort. 

Another important aspect of "GAME" is the scoring system, which will be implemented in the software. This will create transparency for employees and employers. This scoring system will be a great motivation for workers. 


.The most relevant Stakeholders
* Roland Moder 

* Konrad Renner

* Michaela Würzl

* Cornelia Sammer

NOTE: The expections of the Stakeholders should be fulfilled. 

The expectations of the stakeholders regarding the thesis are: 

* sufficient documentation regarding the arc42 template 
* Fulfillment of the quality goals
* a clear and well-functioning software
* an easy-to-use user interface
