[[section-Stakeholders]]

== Stakeholders
[role="stakeholders"]

* *Thesis supervisor* (contractor side)*:* Roland Moder roland.moder@aon.at
* *Thesis supervisor* (client side)*:* Konrad Renner konrad.renner@arz.at
* *Human resource development:* Michaela Würzl michaela.wuerzl@arz.at, 
Cornelia Sammer cornelia.sammer@arz.at

*_Expectations_*:

pass:[<u>Roland Moder</u>]: +
He expects the diploma thesis to run smoothly and be completed within a reasonable time, this means it has to be completed by the end of April. Furthermore, the diploma students should fulfill the requirements for a diploma thesis. Furthermore, there should be a sufficient documentation of the work done.


pass:[<u>Konrad Renner</u>]: +
He expects the software to contain a scoring system that records the learning progress of every member, which can be evaluated and compared.

Er erwartet sich, dass das System ein Punktesystem beinhaltet, welches Lernfortschritte aufzeichnet, welche wiederum bewertet und verglichen werden können. Weiters wird von ihm erwartet, dass die Aufgabenstellungen selbstständig gepflegt werden können, das heißt wenn alle Aufgaben auf der Platform erfüllt worden sind, dann soll es eine Möglichkeit für Trainer geben, neue Aufgaben reinstellen zu können.

pass:[<u>Michaela Würzl & Cornelia Sammer</u>]: +
Sie erwarten sich eine zeitgerechte Fertigstellung des Projekts, sodass das Konzept bis 31.12.2019, und die Umsetzung bis spätestens Ende April fertig ist. Weiters soll die Software verwendbar und integrierbar sei n, das heißt sie soll für die Mitarbeiter leicht verwendbar sein und das User-Interface sollte nicht schwer zu verwenden sein. 